title: Kalinux's Homepage
page-top-title: Jianhang Miao
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Jianhang Miao 2023-2025. All Rights Reserved.'
site_name: "Jianhang Miao"
site_description: "AI"
email: "kalinux_153@163.com"
